version: 2
jobs:
  test-swift-5.0:
    docker:
      - image: library/swift:5.0
    steps:
      - checkout
      - run:
          name: 'XXX: Test can run after ran swift test once'
          command: swift test || true
      - run:
          name: Test
          command: swift test

workflows:
  version: 2
  build:
    jobs:
      - test-swift-5.0
